### ISSUE TITLE
parser creating an incorrect key-value pair

### ISSUE THREAD

**Issue by iDiogenes** [cyberdelia/logfmt-ruby#8]
Hello, 

I noticed an issue when using this gem to parse my HTTP request logs. I have a path that has an equals sign in it and the parser is breaking my path into two key-value pairs, which is not correct. To reproduce run the following:

`Logfmt.parse("path=/mykey=/morepath format=html")`

The result is:
`{"path"=>"/mykey", "/morepath"=>true, "format"=>"html"}`

However, the result should be:
`{"path"=>"/mykey/morepath", "format"=>"html"}`

Cheers,

**Comment by alexandrz** [comment]
The result should be `{"path"=>"/mykey=/morepath", "format"=>"html"}`

Fixed by #10
